import {
  IconToolsKitchen2,
  IconShoppingCart,
  IconCoffee,
  IconCar,
  IconDeviceGamepad2,
  IconHome,
  IconShirt,
  IconStethoscope,
  IconGift,
  IconTools,
  IconPlus,
  IconWallet,
  IconCash,
  IconCreditCard,
  IconBuildingBank,
  IconPigMoney,
  IconReceipt,
  IconCalculator,
  IconBus,
  IconTrain,
  IconPlane,
  IconGasStation,
  IconBike,
  IconMovie,
  IconMusic,
  IconBook,
  IconCamera,
  IconDeviceMobile,
  IconDeviceTv,
  IconBallTennis,
  IconSwimming,
  IconWalk,
  IconPizza,
  IconBeer,
  IconGlass,
  IconCake,
  IconApple,
  IconIceCream,
  IconLamp,
  IconHammer,
  IconPaint,
  IconBed,
  IconSofa,
  IconGardenCart,
  IconTree,
  IconFlower,
  IconPill,
  IconVaccine,
  IconHeart,
  IconBrain,
  IconEye,
  IconSchool,
  IconLanguage,
  IconBabyCarriage,
  IconDog,
  IconCat,
  IconUsers,
  IconUser,
  IconStar,
  IconTrash,
  IconEdit,
  IconSettings,
  IconBell,
  IconCalendar,
  IconClock,
  IconFlag,
  IconTag,
  IconBookmark,
  IconMapPin,
  IconCompass,
  IconPlaneDeparture,
  IconHotelService,
  IconPhoto,
} from "@tabler/icons-react";
import React from "react";

export const AVAILABLE_ICONS = [
  { name: "food", component: IconToolsKitchen2 },
  { name: "coffee", component: IconCoffee },
  { name: "shop", component: IconShoppingCart },
  { name: "car", component: IconCar },
  { name: "game", component: IconDeviceGamepad2 },
  { name: "health", component: IconStethoscope },
  { name: "home", component: IconHome },
  { name: "clothes", component: IconShirt },
  { name: "gift", component: IconGift },
  { name: "work", component: IconTools },
  { name: "wallet", component: IconWallet },
  { name: "cash", component: IconCash },
  { name: "credit-card", component: IconCreditCard },
  { name: "bank", component: IconBuildingBank },
  { name: "piggy", component: IconPigMoney },
  { name: "receipt", component: IconReceipt },
  { name: "calculator", component: IconCalculator },
  { name: "bus", component: IconBus },
  { name: "train", component: IconTrain },
  { name: "plane", component: IconPlane },
  { name: "gas", component: IconGasStation },
  { name: "bike", component: IconBike },
  { name: "movie", component: IconMovie },
  { name: "music", component: IconMusic },
  { name: "book", component: IconBook },
  { name: "camera", component: IconCamera },
  { name: "phone", component: IconDeviceMobile },
  { name: "tv", component: IconDeviceTv },
  { name: "sports", component: IconBallTennis },
  { name: "swim", component: IconSwimming },
  { name: "walk", component: IconWalk },
  { name: "pizza", component: IconPizza },
  { name: "beer", component: IconBeer },
  { name: "wine", component: IconGlass },
  { name: "cake", component: IconCake },
  { name: "apple", component: IconApple },
  { name: "ice-cream", component: IconIceCream },
  { name: "lamp", component: IconLamp },
  { name: "hammer", component: IconHammer },
  { name: "paint", component: IconPaint },
  { name: "bed", component: IconBed },
  { name: "sofa", component: IconSofa },
  { name: "garden", component: IconGardenCart },
  { name: "tree", component: IconTree },
  { name: "flower", component: IconFlower },
  { name: "pill", component: IconPill },
  { name: "syringe", component: IconVaccine },
  { name: "heart", component: IconHeart },
  { name: "brain", component: IconBrain },
  { name: "eye", component: IconEye },
  { name: "school", component: IconSchool },
  { name: "language", component: IconLanguage },
  { name: "baby", component: IconBabyCarriage },
  { name: "dog", component: IconDog },
  { name: "cat", component: IconCat },
  { name: "users", component: IconUsers },
  { name: "user", component: IconUser },
  { name: "star", component: IconStar },
  { name: "trash", component: IconTrash },
  { name: "edit", component: IconEdit },
  { name: "settings", component: IconSettings },
  { name: "bell", component: IconBell },
  { name: "calendar", component: IconCalendar },
  { name: "clock", component: IconClock },
  { name: "flag", component: IconFlag },
  { name: "tag", component: IconTag },
  { name: "bookmark", component: IconBookmark },
  { name: "map-pin", component: IconMapPin },
  { name: "compass", component: IconCompass },
  { name: "takeoff", component: IconPlaneDeparture },
  { name: "hotel", component: IconHotelService },
  { name: "photo", component: IconPhoto },
] as const;

export type IconName = (typeof AVAILABLE_ICONS)[number]["name"];

export const IconRenderer: React.FC<{ name: IconName; size?: number }> = ({
  name,
  size = 16,
}) => {
  const Icon =
    AVAILABLE_ICONS.find((i) => i.name === name)?.component || IconPlus;
  return <Icon size={size} />;
};
